name: Score
main: me.hwei.bukkit.scoreplugin.ScorePlugin
version: 0.6
description: Give score of buildings for each other.
author: HWei
database: true
commands:
  score:
    aliases: scr
    description: Score plugin developed by HWei.
    usage: Type /scr ? to get help.
permissions:
  score.*:
    description: Gives access to all.
    children:
      score.admin: true
  score.admin:
    description: Allows you to manage Score.
    default: op
    children:
      score.use: true
      score.open: true
      score.clear: true
      score.close: true
      score.maxreward: true
      score.moreinfo: true
      score.break: true
      score.reload: true
      score.forcedscore: true
  score.use:
    description: Allows you to get info, give score, list score signs and tp to one of them.
    default: true
    children:
      score.create: true
      score.score: true
      score.info: true
      score.list: true
      score.tp: true
  score:
    default: true
    description: View plugin info.
  score.create:
    description: Create a score sign.
  score.open:
    description: Open a score sign.
  score.score:
    description: 'Give a score. (Range: 0.0~10.0)'
  score.forcedscore:
    description: 'Set or unset a forced score. (Range: 0.0~10.0)'
  score.clear:
    description: Clear all scores given by viewers.
  score.close:
    description: Close a score sign and distrubute rewards.
  score.maxreward:
    description: Set max reward of a score sign.
  score.list:
    description: List recent open score signs.
  score.tp:
    description: Teleport to a score sign in list.
  score.info:
    description: Get infomation about a score sign.
  score.moreinfo:
    description: Get more infomation about a score sign.
  score.break:
    description: Break a score sign.
